adding above dam spring run degree days
Reorienting-to-Recovery/DSMtemperature pull request #4
Opened 2023-10-03 23:45 UTC by MaddeeRubenson

adding a new and more favorable degree day for spring run which never exceeds a temperature of 17 degrees C. 

Is 17 the correct threshold?

2023-10-23 19:02 UTC, ergz approved these changes
looks good!

2023-10-27 18:48 UTC, ErinCain requested changes
Few updates that you an finish after I talk to the tech team on Monday.

2023-10-27 18:48 UTC, ErinCain commented on data-raw/prepare_data_for_model.R
> +# TODO: is 17 the correct threshold value. Double check. Explore how the threshold affects output
This says 17 but looks like below you have it actually at 13. Please update the comment (I will check with tech team on Monday about the temperature threshold)

2023-10-27 18:48 UTC, ErinCain commented on data-raw/prepare_data_for_model.R
> +degree_days_2018_2019_sr_abv_dam <- generate_degree_days(monthly_mean_temperature_2018_2019_abv_dam,
`hec_version` should be "2018 & 2019 Hec5q" not "2008 & 2009 Hec5q" since we are doing it for 2018 2019 temps.

2023-10-27 18:48 UTC, ErinCain commented on data-raw/prepare_data_for_model.R
> +## run of river
I know we are likely not even using this Run of River temps but good to keep temp threshold consistent. Maybe assign a temp_threshold <- 13 (or whatever tech team decides on) above and then use that throughout so we do not have to change in 8 places.

2023-11-02 23:48 UTC, merged